### ISSUE TITLE
PubMed pretrain corpus

### ISSUE THREAD

**Issue by ntubertchen** [dmis-lab/biobert#108]
Hi,

In your paper you mentioned pretraining using PubMed abstract for 1M steps.

You also mentioned separately about the PubMed abstract contains 4.5B words.

How you further verify that 4.5B is actually the 29M articles you mentioned in introduction or you did some fut off. 

Sincerely

**Comment by jhyuklee** [comment]
The 29M stats are from https://en.wikipedia.org/wiki/PubMed as I remember but the exact number from here (https://github.com/naver/biobert-pretrained#pre-training-corpus) may be slightly different. Thanks.
