### ISSUE TITLE
downloading datasets

### ISSUE THREAD

**Issue by EmilyAlsentzer** [dmis-lab/biobert#11]
I'm unable to download the datasets linked in the repo. The link takes me to gofile.me, but then I get an error when I click download. Is anyone else having trouble with this?

**Comment by jhyuklee** [comment]
It seems that the links don't work on some environment. We will update them with other links such as google drive links.

**Comment by EmilyAlsentzer** [comment]
Great, thanks for the quick reply. Looking forward to it.

**Comment by wonjininfo** [comment]
Hi Emily, 
We uploaded the datasets on google drive, and updated links in README.
Thanks!

**Comment by EmilyAlsentzer** [comment]
Great, thanks. Closing the issue.
