### ISSUE TITLE
Get embedding vector without randomicity

### ISSUE THREAD

**Issue by Zhuph31** [dmis-lab/biobert#112]
I am using extract_features.py to get embedding for words and sentences. But I found that it gives different output for the same input every time. How can I set the model so I can get the same embedding for the same input every time? Thank you for your time

**Comment by maziyarpanahi** [comment]
I am experiencing random contextualized embeddings with the same input when I am loading the model from the provided checkpoints

**Comment by jhyuklee** [comment]
Assuming that you have set the random seed (for tf, numpy, etc), it could be due to the nondeterministic behavior of GPUs. Could you try it with CPU and see if they are the same? And I think even with GPUs, the slight difference wouldn't matter a lot.
