### ISSUE TITLE
Provide checkpoints to huggingface community

### ISSUE THREAD

**Issue by MFreidank** [dmis-lab/biobert#114]
Hi,
It seems to me that there are many people that want to use BioBERT from [huggingface/transformers](https://github.com/huggingface/transformers) (examples from this repository include: #106, #98, #66, #65, #58)
This is possible already, by converting checkpoints, but could be made a lot easier by [uploading converted model checkpoints to the huggingface model gallery](https://github.com/huggingface/transformers#quick-tour-of-model-sharing).

I could take care of conversion and uploading and we could namespace the checkpoints with `dmis-lab` in the registry to indicate their origin.

@jhyuklee @wonjininfo Could you please let me know if this would be of interest to you?

**Comment by jhyuklee** [comment]
Hi, I think it's nice to upload the converted checkpoints as we already have some BioBERT applications in PyTorch (like https://github.com/dmis-lab/BioSyn). I'll take a look at the model gallery and let you know if we need help. Thanks.

**Comment by MFreidank** [comment]
@jhyuklee Fantastic! Please let me know if you need help and inform me when the checkpoints are available - also got an application that could benefit :)

**Comment by Santosh-Gupta** [comment]
Would love this as well, particularly those trained on question and answering.

**Comment by arjun-bhatt** [comment]
Also interested!

**Comment by Santosh-Gupta** [comment]
I believe the hf model repo already has several variations on biobert

**Comment by MFreidank** [comment]
@Santosh-Gupta yes, they do; but from what I can tell they are as of now uploaded by data scientists unrelated to this project. I'd prefer to have officially backed checkpoints that can be assumed to be:
* stable
* up to date
* properly pre-trained as per published results

Hence I opened this issue, hope it makes sense.

**Comment by jhyuklee** [comment]
Hi all, we have implemented the PyTorch version of BioBERT in https://github.com/dmis-lab/biobert-pytorch.

You can check them from our model gallery: https://huggingface.co/models?search=dmis-lab

**Comment by MFreidank** [comment]
Awesome!! Thank you @jhyuklee
