### ISSUE TITLE
 convert pytorch_model.pt [BioBERT-Base v1.1 (+ PubMed 1M)] to pytorch_model.onnx (ONNX)

### ISSUE THREAD

**Issue by pumpkinband** [dmis-lab/biobert#115]
i use this to convert pytorch_model.pt to pytorch_model.onnx
```

from torch.autograd import Variable
import torch.onnx
import torchvision
import torch

dummy_input = Variable(torch.randn(1, 3, 256, 256))
model = torch.load('./pytorch_model.pt')
torch.onnx.export(model, dummy_input, "pytorch_model.onnx")
```

ERROR :- `The expanded size of the tensor (256) must match the existing size (3) at non-singleton dimension 3.  Target sizes: [1, 3, 256, 256].  Tensor sizes: [1, 3]`

Are my `dummy_inputs` incorrect ?

**Comment by jhyuklee** [comment]
Hi all, we have implemented the PyTorch version of BioBERT in https://github.com/dmis-lab/biobert-pytorch. Thanks!
