### ISSUE TITLE
RE gives an error

### ISSUE THREAD

**Issue by YuliaInn** [dmis-lab/biobert#119]
I use TensorFlow-gpu 1.15.2. Biobert diretcory is biobert-v1.1-large which contains the following files:
biobert-v1.1-large/bert_config.json  model.ckpt-1000000.data-00000-of-00001  model.ckpt-1000000.index  model.ckpt-1000000.meta  vocab.txt

When I execute this query from the github README:
 
python run_re.py --task_name=$TASK_NAME --do_train=true --do_eval=true --do_predict=true --vocab_file=$BIOBERT_DIR/vocab.txt --bert_config_file=$BIOBERT_DIR/bert_config.json --init_checkpoint=$BIOBERT_DIR/model.ckpt-1000000 --max_seq_length=128 --train_batch_size=32 --learning_rate=2e-5 --num_train_epochs=3.0 --do_lower_case=false --data_dir=$RE_DIR --output_dir=$OUTPUT_DIR
 
Looks like the training part works, but then it gives me this error
 
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./biobert-v1.1-large//model.ckpt-1000000

Should I train and predict separately instead?

**Comment by wonjininfo** [comment]
Hi, 
Sorry for the late reply. I can see two slashes from your error code :  `./biobert-v1.1-large//model.ckpt-1000000`. 
It looks like your environmental variable $BIOBERT_DIR contains a slash at the end (like `./biobert-v1.1-large/`).
Please try them without ending slash.
You can check the environmental variable with `echo $BIOBERT_DIR` commend.
