### ISSUE TITLE
tensorflow-gpu==1.11.0 requirement means <= python3.6

### ISSUE THREAD

**Issue by JohnWSteill** [dmis-lab/biobert#120]
Just walked a lab mate through this, so thought I'd leave a note. If you get:

"ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.11.0 (from -r requirements.txt (line 1)) (from versions: 1.13.1,..."

You're probably using python 3.7 or 3.8. 

It's possible it will work if you edit requirements.txt to a later version number (it's documented as <2.0) but didn't test it.

**Comment by jaimeenahn** [comment]
I'm using python 3.7.7. however, I got the same error

`ERROR: No matching distribution found for tensorflow-gpu==1.11.0 (from -r requirements.txt (line 1))`

**Comment by wonjininfo** [comment]
Sorry for the Late Reply and thanks for letting us know the issue. We updated our `requirements.txt` (commit fb9bb00).  
Thanks!
