### ISSUE TITLE
What is in train.csv in the NER datasets? 

### ISSUE THREAD

**Issue by Santosh-Gupta** [dmis-lab/biobert#140]
From the readme

https://github.com/dmis-lab/biobert#named-entity-recognition-ner

>Let $NER_DIR indicate a folder for a single NER dataset which contains train_dev.tsv, train.tsv, devel.tsv and test.tsv.

There is a train.tsv in the NER datasets, but it doesn't seem to be used by run_ner

https://github.com/dmis-lab/biobert/blob/master/run_ner.py#L175

It looks like train_dev.tsv is treated as the train set, so I am wondering what's in train.tsv.

**Comment by wonjininfo** [comment]
Hi Santosh-Gupta,
We used train.tsv and dev.tsv for searching for the hyperparameter setting. 
After we decided on the hyperparameters, we combined train and dev set into train_dev.tsv and used it for the final training dataset (which is a widely used strategy for preceding BioNLP works). 
Thank you.
