### ISSUE TITLE
Addition of new tokens in vocabulary while pre-training BioBERT

### ISSUE THREAD

**Issue by pg427** [dmis-lab/biobert#141]
Hi, 

I'm using the BioBERT embeddings for pre-training a test model and had a question associated with your developed vocabulary for BioBERT. According to your paper, you used the original BERT model vocabulary which contains ~29000 vocabulary tokens, but on downloading the BioBERT embeddings (+Pubmed v1.1), the vocabulary had ~32000 tokens. My question is, were these tokens added manually, or were these automatically inserted into the new vocabulary while pre-training BioBERT on Pubmed? In either case, can you tell me how the addition of the new terms was made?

**Comment by wonjininfo** [comment]
Hi, 
Would you please confirm which vocab file you are looking into?
I just checked vocab.txt from biobert_v1.1_pubmed and got this result: 
```bash
wc -l vocab.txt
28996 vocab.txt

crc32 vocab.txt
a01fdd62
```
Thank you for your interest in our work!
Best,
Wonjin

**Comment by pg427** [comment]
My apologies. I believe I mixed the number of vocabulary tokens for Biobert and Bert(Base) vocabularies. It seems Bert (Base) vocabulary has about 30522 tokens whereas BioBERT has 28996 tokens only. My question still remains to the disparity between the number of tokens in the vocabulary of the model. Can you please elaborate on that ?

**Comment by wonjininfo** [comment]
BioBERT is based on the **cased** model. We haven't changed the ``vocab.txt`.
It seems like the number you reported (30522) is the number of vocabs of **uncased** model.
Thanks,
WonJin

**Comment by pg427** [comment]
Got it. Thank you for the confirmation. My apologies for the confusion.
