### ISSUE TITLE
How do I specify a certain GPU for training when I fine-tuned NER?

### ISSUE THREAD

**Issue by Crucialer** [dmis-lab/biobert#152]
Does the following code in run_ner.py mean to use the GPU?
`
flags.DEFINE_bool("use_tpu", False, "Whether to use TPU or GPU/CPU.")
`
When I set "use_tpu" to "true",I encountered the next problem.
![image](https://user-images.githubusercontent.com/40562250/102183123-4e2f7580-3ee8-11eb-8f99-8bb1eebc6268.png)`
What can i do to solve it？

**Comment by jhyuklee** [comment]
That option is for TPU. If you have GPU installed on your machine, you can use 'CUDA_VISIBLE_DEVICES=0' to designate a specific GPU for your process (in this case 0th GPU). Thanks!
