### ISSUE TITLE
Biobert text classification

### ISSUE THREAD

**Issue by dongfang91** [dmis-lab/biobert#16]
Hello,

Thanks for providing these useful resources.

I saw the code of run_classifier.py is the same as the original Bert repository, I guessed running text classification using BioBERT is the same as using original Bert. Have you tried some bio-medical text classification task? Just curious about how much gain we can get from BioBERT.

**Comment by jhyuklee** [comment]
Yes, biomedical relation extraction tasks in our paper are examples of biomedical text classification. You can use BioBERT for other biomedical text classification tasks, also.

**Comment by oakkas** [comment]
Hi @dongfang91,

Have you figured out how to do classification?
 I am trying to train a classifier for medical records as a binary classifier. Any suggestions?
Thanks

**Comment by nirvana0311** [comment]
> Hi @dongfang91,
> 
> Have you figured out how to do classification?
> I am trying to train a classifier for medical records as a binary classifier. Any suggestions?
> Thanks

Hi @oakkas did you find any success in your classification task. Even am trying a binary classification task on medical records.

**Comment by chocolocked** [comment]
Any suggestions on using biobert for sequence classification?

**Comment by coco07** [comment]
@dongfang91 @oakkas @nirvana0311 Hi people, have anyone of you found how to use BioBERT for text classification?
