### ISSUE TITLE
https://bern.korea.ac.kr/ not accessible

### ISSUE THREAD

**Issue by luisafuss** [dmis-lab/biobert#164]
I get a timeout error when I want to use the [BioBert tool](https://bern.korea.ac.kr/). Is it not available anymore?

**Comment by jhyuklee** [comment]
Hi, currently the server is overloaded so we can't rerun it.

We'll try to fix it within a week. Thanks!

**Comment by jhyuklee** [comment]
It's fixed. Thanks!

**Comment by luisafuss** [comment]
Thank you!

**Comment by trgandhi** [comment]
Hi @jhyuklee, the tool at https://bern.korea.ac.kr/ is unavailable again
