### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by vinicius-cleves** [dmis-lab/biobert#165]
The paper states that the model is trained on 8 GPUs. When I run the ```run_pretraining.py``` script it only uses one GPU, though. Also, it seems like this is the same script used in BERT, and, on their repo, they say that it does not run on multi-GPU. 

How did you manage to have it running on multi-GPUs?

**Comment by jhyuklee** [comment]
Hi, we used our own distributed training system, which is similar to slurm. These days, we often pre-train language models with Huggingface transformers code (PyTorch) and convert it back to tensorflow version whenever needed. (@DSKSD @mjeensung let us know if it needs further clarification)

**Comment by gitblessk** [comment]
I use slurm as well, meet same issue. 
How can I convert it back to tensorflow and run with multi-gpu.
@jhyuklee  can you share some more detail? thanks!
