### ISSUE TITLE
python file to run for fine-tuning on Squad

### ISSUE THREAD

**Issue by telukuntla** [dmis-lab/biobert#20]
Hello, 
I am confused, Do I Need to execute  'run_qa.py' file or 'run_squad.py'  for fine-tuning the pre-trained model on Squad.

**Comment by wonjininfo** [comment]
Hi,
 'run_qa.py' file is identical to 'run_squad.py'. You can use any of them. 
I will delete 'run_squad.py' in next update. 
Thanks

**Comment by telukuntla** [comment]
Thanks for the confirmation.
