### ISSUE TITLE
word embedding vector

### ISSUE THREAD

**Issue by telukuntla** [dmis-lab/biobert#22]
Hello,
May I know what all text resources(corpus) you have used in building word-embedding vector.

Thanks,
Sai Krishna

**Comment by jhyuklee** [comment]
Hi @telukuntla,
we used PubMed and PMC corpus to train BioBERT, and BioBERT has its WordPiece embedding. You can find the corpus in here (https://github.com/naver/biobert-pretrained).

Thank you.

**Comment by telukuntla** [comment]
Thanks for the information,  "BioBERT has its WordPiece embedding" - are you referring to vocab.txt file? also BioBert(or Bert) uses WordPiece embeddings, not word embeddings(word2vec) ? am I correct ? please confirm.

Thanks,
Sai Krishna.

**Comment by jhyuklee** [comment]
Yes. BERT and its variants use WordPiece embeddings. Thanks.

**Comment by telukuntla** [comment]
Thank you
