### ISSUE TITLE
BERT Large or BERT Base?

### ISSUE THREAD

**Issue by telukuntla** [dmis-lab/biobert#24]
Hello,
May I know if BIOBERT is based on Bert Base or Bert Large. I am sorry if you have already mentioned this information.

**Comment by wonjininfo** [comment]
Its based on `BERT-base`

**Comment by telukuntla** [comment]
Thanks for confirming

**Comment by rsanjaykamath** [comment]
Also is it Bert-base cased or uncased? I'm assuming cased as per the flag "do_lower_case", but correct me if I'm wrong.

**Comment by wonjininfo** [comment]
Hi @rsanjaykamath ,
BioBERT is based on BERT-base (cased) model. 
Thanks
Wonjin

**Comment by rsanjaykamath** [comment]
Thanks for the confirmation.

**Comment by winkelman** [comment]
Hi @wonjininfo are there any plans to train/release weights for an uncased model?  Thank you.

**Comment by wonjininfo** [comment]
Hi @winkelman, 
Unfortunately, we do not have plans to train uncased  BioBERT model at the moment. Thank you
