### ISSUE TITLE
extract_features.py 

### ISSUE THREAD

**Issue by telukuntla** [dmis-lab/biobert#25]
Hello, 
I am to trying to extract contextual embeddings by feeding train.json to 'extract_features.py'.  

example: my input file(train.json file) is as follows:
-------------------------------------------------------------------------
{  
   "version":"BioASQ6b",
   "data":[  
      {  
         "title":"BioASQ6b",
         "paragraphs":[  
            {  
               "context":"Spermidine protects against \u03b1-synuclein neurotoxicity. As our society ages, neurodegenerative disorders like Parkinson`s disease (PD) are increasing in pandemic proportions. While mechanistic understanding of PD is advancing, a treatment.",
               "qas":[  
                  {  
                     "question":"What is the association of spermidine with \u03b1-synuclein neurotoxicity?",
                     "id":"56c073fcef6e394741000020",
                     "answers":[  
                        {  
                           "text":"Spermidine protects against \u03b1-synuclein neurotoxicity",
                           "answer_start":0
                        }
                     ]
                  }
               ]
            }]}]}
-------------------------------------------------------------------
**how ever running 'extract_features.py' should only give contextual embeddings of words that are present as part of 'question' ,'context' right?(please correct me if I am wrong), but the result of running 'extract_features.py' is returning an output file with embeddings of all tokens that are present in the input train.json file, like '{', '[', ':',"qas" and meta data like "BioASQ6b". please let me know how can I only get contextual word embeddings of words that are present as part of 'question'  and 'context so that I can feed it to my model.**

**Comment by jhyuklee** [comment]
Hi, it seems that there might be a problem with reading json file.
You can check how extract_features.py read files, and match your inputs.
Thanks.
