### ISSUE TITLE
adding additional features for QA task

### ISSUE THREAD

**Issue by telukuntla** [dmis-lab/biobert#27]
Hi,
my goal is to extract contextual word embeddings from last layer of BioBert and add additional features, before performing QA fine-tuning. please suggest me how to achieve this. also I found that when I print 'final_hidden = model.get_sequence_output()'  to console, tensor shape is getting printed instead of contextual embeddings. yours suggestions are appreciated.

**Comment by jhyuklee** [comment]
Please see https://github.com/dmis-lab/biobert/issues/23 for extracting features from BioBERT.
Thank you.
