### ISSUE TITLE
An analysis paper of BioBERT and BioELMo

### ISSUE THREAD

**Issue by Andy-jqa** [dmis-lab/biobert#28]
(Sorry to advertise our paper here)

Hi all, we have an analysis paper: [Probing Biomedical Embeddings from Language Models](https://arxiv.org/abs/1904.02181), where we show how biomedical domain adaptation works for contextualized embeddings using probing tasks. Expectedly, fine-tuned BioBERT outperforms BioELMo in biomedical NER and NLI tasks. However, as fixed feature extractors BioELMo seems to be superior than BioBERT in our probing tasks.

In addition, we have BioELMo available at https://github.com/Andy-jqa/bioelmo.

**Comment by jhyuklee** [comment]
Nice work! Maybe you could specify which version of BioBERT you used. It seems that you used PubMed (200K), but PubMed + PMC (470K) worked best in our experiments. Thanks :)
