### ISSUE TITLE
What version of tensorflow/CUDA was used?

### ISSUE THREAD

**Issue by bgriffen** [dmis-lab/biobert#30]
I am on tf 1.12 (python 3.6) and the following cuda version and drivers. 

```
biobert$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
biobert$ NVIDIA-SMI 384.130
```

When I run `extract_features.py` I get:

```
...tensorflow/python/client/session.py"
self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
```

I couldn't find the details in the paper, sorry.

**Comment by wonjininfo** [comment]
Our code was tested on tensorflow-gpu  == 1.11.0 and
Cuda version was same as your system : `Cuda compilation tools, release 9.0, V9.0.176`.

If you are using Windows environment, [this comment](https://github.com/tensorflow/tensorflow/issues/21832#issuecomment-415867163) may help you.

Thanks,
Wonjin
