### ISSUE TITLE
ChemProt trainset, develop set, test set in Re_data ?

### ISSUE THREAD

**Issue by CV2014** [dmis-lab/biobert#33]
I can not find chemprot train in REdata where only euadr and GAD sets left, where are those chemprot sets?
thanks

**Comment by jhyuklee** [comment]
Hi CV2014,
due to the license issue of the CHEMPROT dataset, we could not share the pre-processed version of the dataset. please refer to the work of Lim and Kang (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6014134/) in which we followed the exact same pre-processing steps.
Thank you.
