### ISSUE TITLE
NER datasets

### ISSUE THREAD

**Issue by shreyashub** [dmis-lab/biobert#35]
Hi,
Thank you for providing the preprocessed datasets for NER task. But I had a doubt. The BIO tags in the datasets do not contain B-class_name (e.g. B-disease) but contain only BIO tags without the further class specification.
Is this how BioBERT was trained or am I missing something?

**Comment by jhyuklee** [comment]
Hi @shreyashub ,

we trained and tested BioBERT on each NER dataset (possibly with different entity types), and each dataset does not require a multi-class setting.
For instance, NCBI-disease dataset contains only disease mentions, so we do not need to specify further classes in NER. This is very common in biomedical NER datasets where multi-class labels are very hard to obtain.

Thank you.
