### ISSUE TITLE
Why BioBERT is not up on paperswithcode SOTA leaderboard

### ISSUE THREAD

**Issue by shreyashub** [dmis-lab/biobert#36]
The leaderboard for NER tasks on `paperswithcodes` is [here](https://paperswithcode.com/task/named-entity-recognition-ner).
Even after achieving state of the art scores in multiple datasets, why is BioBERT not on those leaderboards?

**Comment by shreyashub** [comment]
Also, you have shown different results for BC5DR- disease and BC5DR-Drug/Chemical. Does that mean you trained two different models for them, or is it a classwise score for a single model?

**Comment by jhyuklee** [comment]
Hi @shreyashub ,
we haven't recorded our scores in the paperswithcodes site.

Thanks.
