### ISSUE TITLE
Distilled Version of biobert

### ISSUE THREAD

**Issue by leonweber** [dmis-lab/biobert#40]
Hello, thanks for your great work! Do you have any plans on providing a distilled version (https://medium.com/huggingface/distilbert-8cf3380435b5) of BioBERT?

**Comment by jhyuklee** [comment]
Hi, currently we do not have plans for making distilled versions of BioBERT. We are now focusing on building bigger and better pre-trained models. But I agree that we will need the distilled version of it in the future. Thanks!

**Comment by omidrohanian** [comment]
@leonweber Hi, if you are still interested in compact distilled versions of BioBERT and other biomedical language models, you can have a look at DistilBioBERT, TinyBioBERT, and a few other efficient lightweight models all available from Huggingface at: https://huggingface.co/nlpie

Here is also a link to the preprint version of the paper: 
https://arxiv.org/pdf/2209.03182.pdf

Github repo:
https://github.com/nlpie-research/Compact-Biomedical-Transformers

**Comment by jhyuklee** [comment]
@omidrohanian This is great! Thanks for your contribution :) (cc'd @wonjininfo FYI)
