### ISSUE TITLE
What are the PubMed & PMC text that you've used?

### ISSUE THREAD

**Issue by yonatanbitton** [dmis-lab/biobert#42]
I want to access the same variants of PubMed & PMC articles you've used in the pre-processing.
Are they available to download somewhere? 
I've checked the NLM site but there are lots of versions and options. 

Thanks

**Comment by andreasgrv** [comment]
The authors have some links here: [https://github.com/naver/biobert-pretrained#pre-training-corpus](https://github.com/naver/biobert-pretrained#pre-training-corpus`)

**Comment by jhyuklee** [comment]
The date of PubMed and PMC dump is 2019.1.2. Thanks.
