### ISSUE TITLE
Question regarding BioASQ training dataset

### ISSUE THREAD

**Issue by kuhanw** [dmis-lab/biobert#43]
Dear Biobert authors,

We are trying to reproduce some of the results from the BioASQ QA task. In Table 6 of the BioBert paper the number of training data points in the 4B, 5B, 6B datasets are 327, 486, 618 respectively.  However in the json files, BioASQ-train-factoid-4b.json, BioASQ-train-factoid-5b.json and BioASQ-train-factoid-6b.json I find there are 209, 325 and 439 unique questions respectively. Why is there a difference between these?

Are the numbers quoted in Table 6 prior to the unanswerable questions being removed? Referencing this passage: "However, we observed that about 30% of each BioASQ factoid
dataset was unanswerable in the extractive setting as the exact answer
phrases did not appear in the given passages. Like Wiese et al. (2017), we
excluded the unanswerable questions from the training sets, but regarded
them as wrong predictions in test sets"

Thank You,

Kuhan

**Comment by jhyuklee** [comment]
Hi @kuhanw,

yes, you are right. The provided datasets is pre-processed as mentioned in the paper. Thanks.
Jinhyuk
