### ISSUE TITLE
Reproducing RE results using CHEMPROT datasets

### ISSUE THREAD

**Issue by ibrahimishag** [dmis-lab/biobert#45]
Dears,
Thank you very much for making your contribution open to the public. I am **trying to reproduce your results** of the **Relation Extraction**. Looking at the **run_re.py** inside the  **BioBERTChemprotProcessor class**, I noticed you used **five class labels**. Namely, when looking at the list returned by **get_labels method at line 438**, I can see the classes are : **["cpr:3", "cpr:4", "cpr:5", "cpr:6", "cpr:9", "false"].** My Question is:
Does **"false"** as a class label stand for the **non-relation case**?, or it **refers to another type of relation like "cpr:10"?**.

-----
I have got access to the CHEMPROT dataset from SCiBERT [https://github.com/allenai/scibert]

**Comment by jhyuklee** [comment]
Hi @ibrahimishag,

the "false" label stands for the non-relation case. Thanks.

Jinhyuk
