### ISSUE TITLE
NER and RE Prediction for raw sentence

### ISSUE THREAD

**Issue by zhang-zeyu** [dmis-lab/biobert#47]
Thank you for the useful tools.

I saw the prediction mode (--do_predict=true) is for evaluation, so how to apply our own data for the inference? Could you please give me some hints?

**Comment by wonjininfo** [comment]
Hi, @zhang-zeyu 
If you only want to inference and do not wish to train on your own data, please make `--do_predict` as true and `--do_train` as false. Make sure to set `--init_checkpoint=` as the path containing your pre-trained model.

**Comment by CCYChongyanChen** [comment]
> Hi, @zhang-zeyu
> If you only want to inference and do not wish to train on your own data, please make `--do_predict` as true and `--do_train` as false. Make sure to set `--init_checkpoint=` as the path containing your pre-trained model.


Hi wonjin, where could I find the path containing my pre-trained model? Is it in the Output_dir, and is the best checkpoint file? e.g., the model.ckpt-2571?
Thank you.
