### ISSUE TITLE
NER dataset

### ISSUE THREAD

**Issue by ibrahimishag** [dmis-lab/biobert#48]
Dear BioBERT crew,
Again thank you so much for providing this great contribution and the recent BERN. My question is: **What is the purpose of 'train.tsv' file?** 
Because it is **not used in the run_ner.py**. Please explain this.

Thanks in advance,
Ibrahim.

**Comment by jhyuklee** [comment]
Hi,

since most prev works use both train and dev sets for training models and testing them, our scripts are also based on train_dev.tsv files for NER.
If you wish to use train.tsv only, you can change it in run_ner.py.

Thanks.
