### ISSUE TITLE
Reproducing RE scores from the paper

### ISSUE THREAD

**Issue by swethmandava** [dmis-lab/biobert#49]
I'm trying to reproduce the RE scores from the paper for chemprot with F1 = 76.17 and have been unsuccessful so far using this checkpoint *BioBERT v1.1 (+ PubMed 1M) - based on BERT-base-Cased (same vocabulary)* https://drive.google.com/file/d/1R84voFKHfWV9xjzeLzWBbmY1uOMYpnyD/view?usp=sharing

Is there a recipe that worked best or how were the scores computed? Thanks!

**Comment by jhyuklee** [comment]
Hi, what score did you get?

**Comment by swethmandava** [comment]
74.68 is my best yet

**Comment by jhyuklee** [comment]
I guess then the difference would be due to 1) pre-processing rules (Please follow Lim and Kang https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6014134/), or 2) (low chance but possibly) random seed.

Thanks.

**Comment by swethmandava** [comment]
Thanks, looks like it was preprocessing.
I can reproduce the scores if I use https://github.com/arwhirang/recursive_chemprot/tree/master/Demo/tree_LSTM/data dataset

Will the preprocessing scripts be made available?
