### ISSUE TITLE
ner_detokenize

### ISSUE THREAD

**Issue by phu5ion** [dmis-lab/biobert#5]
Hi,

Thank you for your files and codes; they are very helpful as I am new to NLP.

I have processed my NER dataset with BioBert and have tried to get entity-level metrics using the provided ner_detokenize.py script. However I met with an error:
`Error! : len(ans['labels']) != len(bert_pred['labels']) : Please report us`

It seems that the error occurs because of two things:
1. Sometimes Bert's wordpiece tokenization does not result in adding a "##" in front of the word. E.g. I have a word token "2013-10-23" in test.tsv and Bert will tokenise it to "2013" "-" "10" "-" "23". Therefore combining words based on whether there is a "##" prefix is not fully accurate for me.
2. I tried to fix this by asking the script to also combine words if the label is 'X'. But this doesn't work all the time as the label is a prediction and not the true label.

I was wondering whether it will be possible to output the true labels from BioBert as well, or do you have any other suggestions/fixes?

Thank you!

**Comment by wonjininfo** [comment]
Hi, 
Sorry for late reply. 
Would you check the comment https://github.com/dmis-lab/biobert/issues/12#issuecomment-469653386 ?
I think the reply I wrote would also be an answer for your issue. 
Thank you for reporting error to us

**Comment by phu5ion** [comment]
Hi,
I understand now, thanks very much.
