### ISSUE TITLE
pre-training from scratch

### ISSUE THREAD

**Issue by vr25** [dmis-lab/biobert#51]
Hi,

I am trying to pre-train BERT kind of model on my dataset (not fine-tune) from scratch; similar to your work on BioBERT. I understand that I need scripts like create_pretraining_data.py, run_pretraining.py to create and then pretrain on my text corpus. Moreover, the text documents should be split sentence-wise separated by blank lines and this is the corpus to create the pre-trained model [[similar to this]](https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/sample_text.txt).

I couldn't find a detailed write-up as to how exactly I should run the scripts and in what order. [This](https://towardsdatascience.com/pre-training-bert-from-scratch-with-cloud-tpu-6e2f71028379) article tried to sum up the steps required to create a pre-trained model from scratch, but I am still not convinced. The documentation for BioBERT is great anyway, but I was wondering if I could get a more elaborate description of the steps followed to create models similar to [BioBERT](https://github.com/naver/biobert-pretrained). It would be extremely helpful for my work.

Thanks.

**Comment by jhyuklee** [comment]
Hi, our pre-training strategies are exactly the same as BERT (Devlin et al., 2018). We used pytorch huggingface implementation of BERT for pre-training (https://github.com/huggingface/transformers).

Thanks.
