### ISSUE TITLE
Label leakage in construction of lines for run_ner.py?

### ISSUE THREAD

**Issue by Lalaland** [dmis-lab/biobert#53]
Hi,

I think there is a potential label leakage in the run_ner.py in that it's leaking label information into the training data.

https://github.com/dmis-lab/biobert/blob/master/run_ner.py#L158 in particular causes information about the label to be leaking into the structure of the examples. For example, consider a dataset where each sentence only has a single O. That line above would make it obvious where the O is because the O would deterministically be in the same location.

I did some ablations and in practice it doesn't seem to affect things too badly, but this might be a good thing to fix.

**Comment by wonjininfo** [comment]
Hi, 
Sorry for my belated reply. 
I fixed most of the token length related bugs and reflected them in the latest comment (801a50). Would you check it [here](https://github.com/dmis-lab/biobert/tree/801a50e36783b4e1b0517968a24e27ffdf72a01b)? 

Thanks!
