### ISSUE TITLE
using wordpiece tokenizer for pre-training

### ISSUE THREAD

**Issue by vr25** [dmis-lab/biobert#55]
Hi,

I'm trying to pre-train BERT for my domain from scratch. I am following this [article](https://towardsdatascience.com/pre-training-bert-from-scratch-with-cloud-tpu-6e2f71028379) where it says google's word-piece tokenizer isn't open source and hence they use sentence-piece tokenizer.

I was wondering what tokenizer you used for creating the pre-trained model.

Thanks!

**Comment by jhyuklee** [comment]
Hi, we used the same tokenizer used by Google's BERT (https://github.com/google-research/bert). Thanks.
