### ISSUE TITLE
NCBI-disease dataset

### ISSUE THREAD

**Issue by ssavvi** [dmis-lab/biobert#56]
Is anyone able to tell me what the NCBI-Disease NER labels/annotations are ? There is O, B and I? 
array(['O', 'B', 'I'], dtype=object). I assume abbreviations for 3 labels just unsure ? Thank you

**Comment by jhyuklee** [comment]
Hi, please see here (https://en.wikipedia.org/wiki/Inside–outside–beginning_(tagging)) for BIO tagging. Thanks.
