### ISSUE TITLE
Unable to replicate the results shown for QA task

### ISSUE THREAD

**Issue by ahmednasserswe** [dmis-lab/biobert#57]
Hi there,

Could you share the hyperparams used to pretrain BioBert on Squad dataset? I am unable to replicate the results shown on your repo for the QA task. 

Thanks!

**Comment by wonjininfo** [comment]
Hi, 
We used the exact same parameter suggested by google BERT repo. Please check [this section](https://github.com/google-research/bert#squad-11).

```
python run_squad.py \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --do_train=True \
  --train_file=$SQUAD_DIR/train-v1.1.json \
  --do_predict=True \
  --predict_file=$SQUAD_DIR/dev-v1.1.json \
  --train_batch_size=12 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --output_dir=/tmp/squad_base/
```

Thanks!
WonJin

**Comment by jhyuklee** [comment]
You can also see here (https://github.com/dmis-lab/bioasq-biobert) for BioBERT based BioASQ models.
