### ISSUE TITLE
Strange Results with Huggingface

### ISSUE THREAD

**Issue by vthost** [dmis-lab/biobert#58]
Hi, 
I transformed the Pubmed 1.1 model to pytorch and trained on Squad v1.1. 
The validation results of that look ok to me: {"exact_match": 72.67738883632923, "f1": 83.0252257015435}

However when I run on BioASQ and evaluate using the BioBERT code I get very low values. I only tested on 4B_1 so far:
0.0 0.05128205128205128 0.5128205128205128 0.17635327635327633 0.0 0.0 0.0 0.0 0.0 0.0

I also tried the very new pretrained model from the BioBERT BioASQ repository but there get similar results:
0.0 0.07692307692307693 0.4358974358974359 0.16019536019536018 0.0 0.0 0.0 0.0 0.0 0.0

Do you maybe have any idea where I can look for a bug?

**Comment by vthost** [comment]
On the other datasets it's slightly better, but not comparable at all to the paper numbers:

**Comment by jhyuklee** [comment]
Hi, did you find the bug?

**Comment by vthost** [comment]
Thanks for coming back to me! I found some but still cannot fully reproduce the results. In one issue, I read "Since the size of each test dataset is quite small, I suggest you use all three of datasets (4b/5b/6b)."
Did you actually do this to obtain the results in the paper?

**Comment by jhyuklee** [comment]
No, for each dataset (4b, 5b, 6b), we only use each given training set, but not mix them.
Thanks.

**Comment by wonjininfo** [comment]
Hi sorry for my ambiguous comment. Yes I mentioned `Since the size of each test dataset is quite small, I suggest you use all three of datasets (4b/5b/6b).`, but it means "please take account of test scores of all three datasets to evaluate the model".

Please use corresponding train and test datasets (for example, 6b train dataset for 6b test dataset and 5b train for 5b test...)

Also would you please check once again that you are using recent version of qa datasets and the codes (especially transform file on biocode folder)?

**Comment by vthost** [comment]
Thanks, I read it in this way, but I wanted to make sure. I now obtain comparable results!

**Comment by wonjininfo** [comment]
Thanks for your efforts on reproduction!

**Comment by Santosh-Gupta** [comment]
Would love to have the weights for this, might be useful for covid papers.

**Comment by vthost** [comment]
@Santosh-Gupta I'd be happy to help, I uploaded them here: https://github.com/vthost/biobert-pretrained-pytorch

**Comment by Santosh-Gupta** [comment]
Thanks!

**Comment by abdallah197** [comment]
@vthost can you share how did you run the evaluation  of BioASQ after fine-tuning the models

**Comment by vthost** [comment]
I am not exactly sure about what you mean, I ran the code provided in the repo...

**Comment by abdallah197** [comment]
I mean how did you use the pytorch checkpoints of hugging face to generate
similar predictions to the file predictions.json?

**Comment by vthost** [comment]
It's some time ago... but as far as I remember, I adapted their run_squad script. I used these models: https://github.com/vthost/biobert-pretrained-pytorch

**Comment by abdallah197** [comment]
In case you still have the adapted script, can you share it?

**Comment by vthost** [comment]
I have added some explanation to my repo. I am not sure if this is enough. I had extended the code for other purposes too. If you have issues let me know. Then I could send you the original files..

**Comment by abdallah197** [comment]
Hi @vthost 

Do you by any chance happen to have the BioASQ datasets version that you ran the evaluation on? they changed the preprocessing mechanism and that's why the code is not working anymore.

**Comment by vthost** [comment]
I sent you an email.
