### ISSUE TITLE
Raw Text named entity recognition prediction!

### ISSUE THREAD

**Issue by AndreasSaka** [dmis-lab/biobert#59]
I read the previous issues on how to fine tune biobert, however I still do not understand how to use the fine tuned model to extract entities from a raw unlabeled text. Is there anyone that can provide some step by step procedure?

Reminder: I do know how to fine tune Biobert. The issue is how to use the fine tuned model in order to extract entities from raw unlabeled text!

**Comment by jhyuklee** [comment]
Hi. If you do not know how to use the code, please use the BioBERT-based NER tool, BERN (https://bern.korea.ac.kr) that supports what you want to do. Thanks.
