### ISSUE TITLE
How to ask specific questions?

### ISSUE THREAD

**Issue by jsf0433** [dmis-lab/biobert#60]
How to ask specific questions?

**Comment by wonjininfo** [comment]
Would you please elaborate your issue? 

Our model is only capable of handling extractive QA datasets (especially SQuAD v1 format dataset). It means you need to input question and corresponding context passage, where the answer exists, pair to our model. 
Thanks! 
Wonjin

**Comment by jsf0433** [comment]
I've followed your information to install, I still don't know how to do next, Would you like to offer more detail?  offer me some examples is better, Thank U

**Comment by jhyuklee** [comment]
Hi, given your description, it is very difficult for us to provide more details. Please be more specific. What do you want to do? Thanks.

**Comment by jsf0433** [comment]
I wanna try to issue a question, then get answer list, Where can I get a simple example like I asked?

**Comment by goaaron** [comment]
@jsf0433  i think you will have to format the input questions in the BioASQ format. Definitely not something very nice. But perhaps you can write a simple script to wrap the question with the relevant context and store it in json

**Comment by jhyuklee** [comment]
You have to use the BioASQ format unless you write a script as recommended above. Thanks.
