### ISSUE TITLE
NER finetuning - checkpoint problem

### ISSUE THREAD

**Issue by zampierimatteo91** [dmis-lab/biobert#61]
Hi all, 
Sorry to bother you with stupid mistakes.

I am trying to fine-tune the NER model to later run a prediction on a dataset I have.
I am trying to run the fine-tuning on a dataset I have, formatted as the ones you provided.
I downloaded the `biobert_v1.1_pubmed` model, but it doesn't contain any `model.ckpt` per se; instead, there are `model.ckpt-1000000.meta`, `model.ckpt-1000000.index`, and `model.ckpt-1000000.data-00000-of-00001`.

Using one of those gives error though.

Thanks

**Comment by ManousogiannisM** [comment]
Hi,

Based on https://github.com/tensorflow/models/issues/2676#issuecomment-461819896 ,
using just `model.ckpt` (without `.index ` or `-1000000.meta`) worked for me.

**Comment by zampierimatteo91** [comment]
Hi @ManousogiannisM ,

Thanks for the reply!

Using `model.ckpt-1000000` worked fine!
I now have to solve just the usage of tensorflow-gpu :p  

Thanks again and good day

**Comment by AndreasSaka** [comment]
@zampierimatteo91  

> I am trying to run the fine-tuning on a dataset I have, formatted as the ones you provided.

can you elaborate on how you performed this task ?
