### ISSUE TITLE
Pre-processing text file

### ISSUE THREAD

**Issue by gnakum** [dmis-lab/biobert#64]
Hi,

Could you explain how have the files train.tsv, test.tsv, etc. have been created? I have a dataset of unannotated text files in which I wish to classify named entities, so could you shed some light on how can I convert my dataset to the formats required for prediction? Thanks!

Edit: I used the functions in tokenization.py to convert my text files to the required format (labeling al tokens as 'O' since I do not have the ground truth annotations). However, when I run python run_ner.py in predict mode, it asks for a devel.tsv file. Can I not obtain predictions without this file? And why is a development set used during prediction time?

**Comment by jhyuklee** [comment]
Hi @gnakum, you can check [BERN](https://github.com/dmis-lab/bern) for inputting your text for NER. See [here](https://github.com/dmis-lab/bern/blob/dd413b71b8c6a8942cc7036d664bcd11297518d8/biobert_ner/run_ner.py#L361) for example. Thanks.
