### ISSUE TITLE
Convert TF into Pytorch for Biobert

### ISSUE THREAD

**Issue by yrf1** [dmis-lab/biobert#65]
Hi, how can I finetune a pretrained biobert using pytorch?

I understand that there are pretrained biobert weights in tensorflow format available for download, and I can convert these weights into pytorch format using `huggingface/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py`.

However, my understanding is that the ordered dict collection of these weight parameters needs to be loaded into pytorch using the `load_state_dict() `function of `nn.module`.

And from my understanding, to do this, I need to have the code of the model architecture available in pytorch but biobert code is written in tensorflow.

So how can I solve this problem?
Help appreciated, thanks!

**Comment by freesinger** [comment]
Hi, you may check huggingface document [here](https://huggingface.co/transformers/converting_tensorflow_models.html), which may be helpful. `Transformer` will output a `pytorch_model.bin` file if you succeed in converting. You can use `torch.load()` to load this file as torch model.
