### ISSUE TITLE
Fine-tuned NER not giving correct results

### ISSUE THREAD

**Issue by shivanik96** [dmis-lab/biobert#69]
I fine-tuned the pre-trained biobert model with the NCBI-disease dataset provided and got the correct eval measures. However, when I am using this fine-tuned model to predict the named entities of my text, it is assigning only to 'O' or 'X' to all the tokens. Can you suggest why this may be happening?

**Comment by AndreasSaka** [comment]
@shivanik96 What kind of text do you have? Is it already annotated?

**Comment by shivanik96** [comment]
No, it is not annotated. I've marked all the words with the 'B' tag at the beginning as the code wants annotated text. I also tried to annotate all words with a 'B' tag except every 10th word which is marked with an 'O' tag. This was done because "_read_tsv" was popping elements until an 'O' is there. I don't know if this is the right approach.
I have fine-tuned the dataset on NCBI-disease dataset and am trying to predict on PubMed abstracts. Is it possible that the word set of the two is different which is leading to such behaviour?

**Comment by teressakim70** [comment]
@shivanik96
I am trying to the same thing: fine-turning BioBERT with NCBI-disease dataset and unfortunately I don't get the same eval statistics, instead the last figure I got was around 69% F measure.
Would it be possible to share your run_ner.py arguments? Also I am interested in how long it took for you to fine-tune?  I used centos CPU 16GB RAM, and took 5-6 days and I am not sure if this is usual

I run the python run_ner.py program with:
 --do_train=true
 --do_eval=true
 --num_train_epochs=5.0
 --init_checkpoint=../biobert_v1.1_pubmed/model.ckpt-1000000

**Comment by jhyuklee** [comment]
Hi @teressakim70, did you try the one in the README?
```bash
$ python run_ner.py --do_train=true --do_eval=true --vocab_file=$BIOBERT_DIR/vocab.txt --bert_config_file=$BIOBERT_DIR/bert_config.json --init_checkpoint=$BIOBERT_DIR/model.ckpt-1000000 --num_train_epochs=10.0 --data_dir=$NER_DIR --output_dir=$OUTPUT_DIR
```
