### ISSUE TITLE
'O' tag is hard-coded to be at position 3

### ISSUE THREAD

**Issue by lfurrer** [dmis-lab/biobert#70]
If the model predicts label 0 (zero), it is corrected to the label at position 3:
https://github.com/dmis-lab/biobert/blob/12b22304de403f8e8d0193d98f952f74b84fbd60/run_ner.py#L634

With the hard-coded labels from `NerProcessor.get_labels()`, this is the "O" label.
However, if you ever change the labels (or just their ordering), this is not necessarily true, in which case the correction produces an arbitrary label.
This behaviour is quite well-hidden!

**Comment by jhyuklee** [comment]
Thanks for letting us know! Does that cause any problem in the current code? If not, we'll add it to our checklist for the code update. Thanks :)

**Comment by lfurrer** [comment]
It's a time bomb. As soon as somebody changes the label set (eg. from IOB to IOBES), it's quite likely that 'O' is no longer at position 3. In that case, there'd be a quite well-hidden bug in the code.
