### ISSUE TITLE
How do I run predictions on a new passage for NER?

### ISSUE THREAD

**Issue by pacejohn** [dmis-lab/biobert#75]
I have been able to do the fine-tuning for NER with no problems.  I am trying to perform NER on an abstract from Pubmed.  Maybe I missed something, but I cannot figure out how to do this?  My question are:

1.  How do I convert the text file where the abstract is saved into a format that can be used for NER?  I was thinking it might be tokenization.py, but I looked at tokenization.py and I can't tell where you specify the file you want tokenized.  

2.  What name should I save the file as to run inference?  In run_ner.py, it appears it only looks at the data_dir, not any specific file.  Is it devel.tsv?

3. Can you please explain what the O, I, B mean in the test.tsv, train.tsv and what O-MISC, I-MISC, etc, mean in NER_result_conll.txt?

My apologies if these questions have already been answered, but I just can't seem to find them.  Thanks in advance for your help!  I just want to know the end-to-end process for performing NER on a new abstract then being able to see and interpret the results.

**Comment by Mayar2009** [comment]
I have the same questions also

**Comment by jhyuklee** [comment]
Hi, this might help: https://github.com/dmis-lab/biobert/issues/73#issuecomment-572431333
