### ISSUE TITLE
BioBERT Pre-trained Models for TF 2.0 or 1.15

### ISSUE THREAD

**Issue by maziyarpanahi** [dmis-lab/biobert#86]
Hi,

I am trying to load and save your pre-trained models in TF 1.15.0 and I have some difficulties. It does load and I am able to save it as saved_model.pb, however, even though it says outputs have 768 shape it only gives me 14 or 20 dimensions for embeddings.

I am guessing there is something with the compatibility of the models with TF 1.15. or TF 2.0. I understand the code is not compatible with TF 2.x but is it possible to make the pre-trained models compatible for at least 1.15.x V1?

Many thanks

**Comment by jhyuklee** [comment]
Hi @maziyarpanahi, the version of TF should have nothing to do with the dimension. The model itself has the same architecture and it also works in PyTorch. Thanks.
