### ISSUE TITLE
Token-Level and entity level metrics

### ISSUE THREAD

**Issue by sirisha-8** [dmis-lab/biobert#89]
Hi ,

There are two metrics generated after prediction .token-level metrics and overall entity-level metrics after running **conlleval.pl** . 

Could you guys elaborate these in detail .What should be considered while reporting. and also it would be helpful if you could tell me the difference between them @jhyuklee @donghyeonk @winkelman @wonjininfo @DSKSD 

Thankyou

**Comment by jhyuklee** [comment]
You have to use the entity-level metric for a fair comparison with previous works. Token level metrics do not actually assess the quality of entity tagging, but just shows a token-level performance. Thanks.
