### ISSUE TITLE
Extra checkpoint initialisation in run_ner.py (Minor)

### ISSUE THREAD

**Issue by antonyscerri** [dmis-lab/biobert#9]
Hi

It looks like in the run_ner.py script you have has an extra call to initialise from a checkpoint (which will cause it to be attempted twice, hopefully without side-effects). Line 416 looks to be unnecessary.

Thanks

Tony

**Comment by wonjininfo** [comment]
Hi, 
Thank you for your report! We reflected this issue and fixed it at commit f8bdd2b 
Best,
WonJin
