### ISSUE TITLE
Pre Training Dataset Preprocessing

### ISSUE THREAD

**Issue by amansinha09** [dmis-lab/biobert#92]
Hi, 
Can you please elaborate the strategies for pre-preprocessing of PubMed Abstracts and PMC Full articles. As in the medical domain research journals to the required formats and how did you use the PubMed XML format for pre training?
Thanks.

**Comment by jhyuklee** [comment]
Hi, we mostly used PubMed abstracts which can be easily obtained from PubMed. We do not provide codes for pre-processing the full text. It requires a lot of heuristics to pre-process them as the formats are inconsistent. Thanks.
