### ISSUE TITLE
About the output file test_results.tsv of run_re.py

### ISSUE THREAD

**Issue by wangxinyi-gsafety** [dmis-lab/biobert#93]
Hi,
Could you please explain the meaning of the data in this output file 'test_results.tsv' which generated from run_re.py? Based on the data below, how can I check the ROC curve?

0.07274711	0.9272528
0.095984295	0.9040157
0.9922472	0.0077527557
0.9926876	0.0073124254
0.09326941	0.9067306
....

thanks!!

**Comment by jhyuklee** [comment]
Hi, regarding the ROC curve, [this](https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html#sphx-glr-auto-examples-model-selection-plot-roc-py) might help. Thanks.

**Comment by AndreasSaka** [comment]
@wangxinyi-gsafety Did you find out what the two columns (the output for Relation Extraction) actually mean?

**Comment by wangxinyi-gsafety** [comment]
@AndreasSaka, until now, I dont' find this out.

**Comment by jhyuklee** [comment]
@SunkyuKim Do you have any idea on that file?

**Comment by SunkyuKim** [comment]
@wangxinyi-gsafety Our relation extraction tasks except chemprot task perform a binary classification that predicts whether a sentence has a relationship. The first and second values of each row mean predicted probabilities of negative and positive label of the given sentence. Normally you can use the second column to get ROC curve.

**Comment by wangxinyi-gsafety** [comment]
@SunkyuKim，thanks a lot.

**Comment by AndreasSaka** [comment]
@SunkyuKim thanks that is great!
