### ISSUE TITLE
BioBERT with bert-as-service

### ISSUE THREAD

**Issue by Manajit89** [dmis-lab/biobert#96]
Hi!

First of all let me begin by thanking you for the pre-trained BERT model which is a life saver. For my latest project, I would like to get to ELMo like contextual embeddings from BioBERT. To reduce the complexity barrier, I resorted to using _bert-as-service_ (https://github.com/hanxiao/bert-as-service), which admittedly accepts pre-trained models. However, when I try to run it I encounter strange errors. I am wondering if it is due to the Tensorflow version or something. According to the documentation of bert-as-service, (https://bert-as-service.readthedocs.io/en/latest/section/faq.html#can-i-use-my-own-fine-tuned-bert-model), one needs to provide just the checkpoint, vocab and bert_config.json, which are all present in the BioBert directory. Despite that, I see the following errors:
![Issue_1](https://user-images.githubusercontent.com/33542824/75041266-8890d780-54bc-11ea-9efe-f6b2914cad34.png)
![Issue_2](https://user-images.githubusercontent.com/33542824/75041274-8b8bc800-54bc-11ea-9866-4234083ac54b.png)

Am I missing something? Is there an easier alternative to get the embeddings without having to set-up the code ecosystem?

Thanks in advance,
Manajit

**Comment by jhyuklee** [comment]
Not familiar with bert-as-service but this (https://github.com/naver/biobert-pretrained/issues/7) might help.

**Comment by Manajit89** [comment]
Thank you very much for this. Not sure how I missed that.

Best,
Manajit
--------------------------------------------------
Manajit Chakraborty
PhD Student,
Faculty of Informatics,
Università della Svizzera italiana (USI),
Lugano 6900, CH
--------------------------------------------------





On 26 Feb 2020, at 12:54 PM, Jinhyuk Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


Not familiar with bert-as-service but this (naver/biobert-pretrained#7<https://github.com/naver/biobert-pretrained/issues/7>) might help.
