### ISSUE TITLE
code for preprocessing

### ISSUE THREAD

**Issue by ardakdemir** [dmis-lab/biobert#97]
Dear Authors,

biobert and biobert-asq use a preprocessed version of the dataset provided by the BioASQ challenge. Specifically, the datasets are converted into squad format so that it can be directly given as input to BERT model. 

Is it possible for you to share the code used for preprocessing so that the model can be applied to the new BioASQ datasets, to increase the reusability of the repository. I am sorry if it is already available in the repository, I could not locate it.

Thanks in advance.

Kind regards 

Arda

**Comment by wonjininfo** [comment]
Dear Arda, 
We (= authors) had discussions about releasing the pre-processing script before. 
We regret to say that we decided not to release the pre-processing code since there are multiple issues (including copyright and PubMed API issues). 

Best regards,
Wonjin

**Comment by ardakdemir** [comment]
I see. Actually, I think sharing only the source-code that converts a json from bioasq format to squad format would help a lot.
